### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by shaolong5**
forth change

### CODE REVIEW

**Comment by behinger** [comment]
hey, you do need to also merge things, you know that right?

**Comment by shaolong5** [comment]
Hello, professor
No, I don’t. I just want to try how to make some changes and show up on the
website.



Benedikt Ehinger ***@***.***>于2024年6月18日 周二12:08写道：

**Comment by behinger** [comment]
ah ok - so you are using it for preview? You dont have to close it all the time, as soon as you push it, the actions are run.

but vfor preview, you can also run it locally (much faster)

**Comment by shaolong5** [comment]
For review the document I edited and see what has changed respectively on
the websites, is  it possible to run locally and not push and I can still
see changes on the website.


Benedikt Ehinger ***@***.***>于2024年6月18日 周二12:17写道：

**Comment by behinger** [comment]
is this a question? include("make.jl") will create a local version in your `docs/build` folder

**Comment by shaolong5** [comment]
Forgot the question mark🤣.  Okk, I’ll take a look at that.

Benedikt Ehinger ***@***.***>于2024年6月18日 周二12:28写道：

**Pull request closed without merging**
